app:
  static-resources:
    - paths: [/forever/**]
      locations: [classpath:/forever/]
      cache: forever
    - paths: [/htmx/**]
      locations: [classpath:/htmx/]
      cache: default
  datasource:
    url: ${R2DBC_URL:r2dbc:h2:file:///../testdb}
  server-root-uri: ${SERVER_ROOT_URI:http://localhost:4000}
  easy-auth:
    protected-area: /app/**
    login-page: /login/
  playground:
    base-dir: /opt/playground
    instance-uuid: ${INSTANCE_UUID:default-app}
    app-id: ${APP_ID:0}
    tell-refresh-endpoint: ${TELL_REFRESH_ENDPOINT:http://localhost:4000/app/default-app/tell-refresh}
    watch-includes:
      - src/main
    watch-excludes:
      - .git