spring:
  thymeleaf:
    cache: false
  webflux:
    base-path: ${DEMO_CONTEXT_PATH:/context-path}
  messages:
    basename: i18n.messages
  servlet:
    multipart:
      max-file-size: 1MB
      enabled: true
  config:
    import:
      - optional:secret.properties
      - app.yaml
  cache:
    cache-names:  tags_list
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
server:
  port: ${SERVER_PORT:8080}
  # servlet:
  #   context-path: /context-path
logging:
  level:
    root: WARN