spring:
  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    # view-names:
    excluded-view-names: freemarker/*, mustache/*, js/*
  freemarker:
    template-loader-path: classpath:/templates/
    view-names: freemarker/*
  mustache:
    check-template-location: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: mustache/*
  # devtools:
  #   add-properties: false
  webflux:
    base-path: /
  messages:
    basename: i18n.messages
  servlet:
    multipart:
      max-file-size: 1MB
      enabled: true
  config:
    import:
      - optional:secret.properties
      - app.yaml
  cache:
    cache-names:  tags_list
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=600s"
server:
  port: ${TOBF_SERVER_PORT:8080}
  # servlet:
  #   context-path: /context-path
logging:
  level:
    root: WARN
    com:
      example:
        springsecurity: DEBUG
    web: DEBUG
